FROM node:22-alpine

WORKDIR /app

COPY ../../package*.json ./

COPY ../../services/shared ./services/shared

COPY . ./services/search-service

RUN npm install --workspaces

WORKDIR /app/services/search-service

EXPOSE 4003

USER node

CMD ["npm", "run", "dev"]
